### ISSUE TITLE
Use EstimateSmartFee RPC call to estimate tx fee after btcd upgrade to v0.23

### ISSUE THREAD

**Issue by gitferry** [babylonchain/vigilante#117]
Currently, tx fee estimation is using `EstimateFee` call which is deprecated.

**Comment by Lazar955** [comment]
we can close [this issue](https://github.com/babylonchain/vigilante/issues/117) as we are using lnd's [EstimateFeePerKW](https://github.com/babylonlabs-io/vigilante/blob/cf21c32f95e86201c8e7b6ab3a5a063d62285122/submitter/relayer/relayer.go#L437). Looks similar to [this](https://bitcoincore.org/en/doc/27.0.0/rpc/util/estimatesmartfee/)

**Comment by gitferry** [comment]
You are right. The lnd's impl for bitcoind is using `EstimateSmartFee` [method](https://github.com/lightningnetwork/lnd/blob/6bd30047c1b1188029e8af6ee8a135cf86e7dc4b/lnwallet/chainfee/estimator.go#L445)
