### ISSUE TITLE
Reporter: potential out-of-mem issue when btclightclient is far behind BTC (not-urgent)

### ISSUE THREAD

**Issue by gitferry** [babylonchain/vigilante#154]
The bootstrapping mechanism of the reporter is subject to potential out-of-mem issue because it caches all the BTC blocks from the base height to the latest. It will be an issue if the `btclightclient` module of Babylon is far behind BTC a lot. This situation is not urgent for now because the liveness of Babylon requires at least a reporter running 24/7. Still, it will be critical if the reporter is down for a long time because we might not be able to restart the reporter due to the out-of-mem issue.

cc @SebastianElvis @gusin13.

**Comment by SebastianElvis** [comment]
Solved by the paginated submission
