### ISSUE TITLE
Need alert when submitting checkpoints with inappropriate epochs

### ISSUE THREAD

**Issue by gitferry** [babylonchain/vigilante#177]
Currently, when receiving checkpoints with invalid epoch number (lower than the last submission) or invalid status (not Sealed), we only log it as error without doing anything. This is because this could be a bug from the Babylon node. However, to capture this issue, we need to export these cases to Prometheus for alerting.

**Comment by Lazar955** [comment]
This can be closed as we do have metrics for this

**Comment by gitferry** [comment]
Thanks for checking!
