### ISSUE TITLE
Submitter refactoring points

### ISSUE THREAD

**Issue by gitferry** [babylonchain/vigilante#178]
Some improvement ideas brought up by @KonradStaniec:
1. `SendCheckpointToBTC` is starting becoming a bit too complex for my taste and handles too much. Imo resendSecondTxOfCheckpointToBTC should be extracted to separate function and handled in main event loop.
2. Before doing rbf, we could check if previous tx is in mempool still. This way we could make sure we are really sending tx with larger fee

**Comment by Lazar955** [comment]
Done in [#57](https://github.com/babylonlabs-io/vigilante/pull/57)
