### ISSUE TITLE
Submitter: add subscriber to Babylond node for Sealed checkpoints

### ISSUE THREAD

**Issue by gitferry** [babylonchain/vigilante#54]
For simplicity, we first implemented a poller to periodically retrieve Sealed checkpoints. But this is not timely. To submit a checkpoint as soon as it becomes Sealed, we need to subscribe the `newly-sealed-checkpoint` events to Babylon and submit Sealed checkpoints in a push-based manner.

**Comment by vitsalis** [comment]
@gitferry Didn't we abandon this methodology?

**Comment by gitferry** [comment]
Yep. Close it now
